apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zcns055nb-nodejs 
  janus-idp.io/tekton: zcns055nb-nodejs
  backstage.io/kubernetes-id: zcns055nb-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zcns055nb-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  