apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zcns055nb-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zcns055nb-nodejs 
  name: zcns055nb-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zcns055nb-nodejs 
